# Generated by Django 4.2.1 on 2023-06-11 18:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(default='', max_length=200)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('subject', models.CharField(choices=[('META', 'META'), ('Programming', 'Programming'), ('Film', 'Film'), ('Music', 'Music'), ('Other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
