# Generated by Django 4.1.6 on 2023-04-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Film', 'Film'), ('Music', 'Music')], max_length=50),
        ),
    ]
