# name: Test Workflow

# on:
#   push:
#     branches: [ main ]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Echo a message
#       run: echo "GitHub Actions is working!"
  
#   test_ssh:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Deploy code
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SERVER_IP }}
#         username: ${{ secrets.SERVER_USER }}
#         key: ${{ secrets.SERVER_SSH_KEY }}
#         passphrase: ${{ secrets.SERVER_SSH_KEY_PASSPHRASE }}
#         script: |
#           cd /var/www/portfolio
#           git pull
#           source env/bin/activate
#           pip install -r requirements.txt
#           cd website
#           python manage.py collectstatic --noinput
#           python manage.py migrate
#           sudo systemctl restart gunicorn

name: Portfolio CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  # run_tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.10'
  #   - name: Install dependencies
  #     run: |
  #       pip install -r requirements.txt
  #   - name: Run Django tests
  #     run: |
  #       cd path/to/your/django/project  # Adjust path
  #       python manage.py test

  restart_gunicorn:
    runs-on: ubuntu-latest
    # needs: run_tests  # Ensures tests run first
    # if: success()  # Only runs if tests pass
    steps:
    - name: Restart Gunicorn service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        passphrase: ${{ secrets.SERVER_SSH_KEY_PASSPHRASE }}
        script: |
            /home/carb/scripts/restart_gunicorn.sh



