name: Test Workflow

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Echo a message
      run: echo "GitHub Actions is working!"
  
  test_ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        passphrase: ${{ secrets.DROPLET_SSH_KEY_PASSPHRASE }}
        script: |
          cd /home/arbelaezch/Personal-Website
          git pull
          source env/bin/activate
          pip install -r requirements.txt
          cd website
          python manage.py migrate
          sudo systemctl restart gunicorn

