name: Portfolio CI/CD Pipeline

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        DJANGO_ALLOWED_HOSTS: "www.christiandonovan.ca christiandonovan.ca localhost 127.0.0.1 [::1]"
        DEBUG: "1"
        SECRET_KEY: "dummy_key_for_tests"
        DEV_DB_ENGINE: "django.db.backends.sqlite3"
        DEV_DB_NAME: ":memory:"
        DEV_DB_HOST: ""
        DEV_DB_USER: ""
        DEV_DB_PASSWORD: ""
        DEV_DB_PORT: ""
      run: |
        cd website
        python manage.py test

  deploy:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development')
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ github.ref == 'refs/heads/main' && secrets.PROD_SERVER_IP || secrets.DEV_SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.MEDITATIONS_PRIVATE_KEY }}
        script: |
          # Deploy to appropriate directory based on branch
          DEPLOY_DIR=${{ github.ref == 'refs/heads/main' && '/var/www/portfolio' || '/var/www/portfolio-dev' }}
          cd $DEPLOY_DIR
          git pull origin ${{ github.ref_name }}
          source env/bin/activate
          pip install -r requirements.txt
          cd website
          python manage.py collectstatic --noinput
          python manage.py migrate
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            sudo /bin/systemctl restart gunicorn
          else
            sudo /bin/systemctl restart gunicorn-dev
          fi