name: Portfolio CI/CD Pipeline

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        cd website
        python manage.py test

  deploy:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development')
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ github.ref == 'refs/heads/main' && secrets.PROD_SERVER_IP || secrets.DEV_SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.MEDITATIONS_PRIVATE_KEY }}
        script: |
          # Deploy to appropriate directory based on branch
          DEPLOY_DIR=${{ github.ref == 'refs/heads/main' && '/var/www/portfolio' || '/var/www/portfolio-dev' }}
          cd $DEPLOY_DIR
          git pull origin ${{ github.ref_name }}
          source env/bin/activate
          pip install -r requirements.txt
          cd website
          python manage.py collectstatic --noinput
          python manage.py migrate
          sudo systemctl restart ${{ github.ref == 'refs/heads/main' && 'gunicorn' || 'gunicorn-dev' }}

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Deployment Status Notification
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "Production deployment completed"
        else
          echo "Development deployment completed"
        fi